# ESLint
#
#   Configuration: http://eslint.org/docs/user-guide/configuring
#   Rules: http://eslint.org/docs/rules/

---
  extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended

  parser: '@typescript-eslint/parser'

  plugins:
    - '@typescript-eslint'
  root: true
  env:
    node: true
    es6: true

  globals:
    Promise: true
    BufferEncoding: readonly

  rules:
    "@typescript-eslint/no-explicit-any": "off"
